version: "3.4"

services:
  app.ids.server:
    container_name: appidsserver-c
    image: appidsserver
    build:
      context: .
      dockerfile: App.IDS.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - "/var/ids-tutorial/appidsserver/logs:/app/logs"
    ports:
      - "5000:80"

  app.order.server:
    container_name: apporderserver-c
    image: apporderserver
    build:
      context: .
      dockerfile: App.Order.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - "/var/ids-tutorial/apporderserver/logs:/app/logs"
    ports:
      - "5001:80"

  app.user.server:
    container_name: appuserserver-c
    image: appuserserver
    build:
      context: .
      dockerfile: App.User.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - "/var/ids-tutorial/appuserserver/logs:/app/logs"
    ports:
      - "5002:80"
